version: '3'
services:
  python-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI_TEST=mongodb://mongodb:27017
      - CURRENT_ENVIRONMENT=test
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - mongodb
    command: "pytest"
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - "27017:27017"
